insert into eerr (prefix, desc) values ("3.1.00","-PRODUCTOS");
insert into eerr (prefix, desc) values ("3.5.00.5010","-REPUESTOS");
insert into eerr (prefix, desc) values ("3.5.00.5020","-SERVICIOS A TERCEROS");
insert into eerr (prefix, desc) values ("3.6","-SERVICIOS EMPRESAS RELACIONADAS");
insert into eerr (prefix, desc) values ("3.9","-OTROS INGRESOS");
insert into eerr (prefix, desc) values ("4.1","-COSTO PRODUCTOS ");
insert into eerr (prefix, desc) values ("4.5","-COSTO REPUESTOS");
insert into eerr (prefix, desc) values ("4.8.00.9010","-OTROS COSTOS");
insert into eerr (prefix, desc) values ("4.8.00.9050","-CASTIGOS");
insert into eerr (prefix, desc) values ("4.9","-CONVENIOS");
insert into eerr (prefix, desc) values ("5.1.00","-PERSONAL");
insert into eerr (prefix, desc) values ("5.1.50","-PERSONAL");
insert into eerr (prefix, desc) values ("5.2.00","-PERSONAL");
insert into eerr (prefix, desc) values ("5.2.50","-PROV INDEMNIZACION");
insert into eerr (prefix, desc) values ("5.3.00","-PERSONAL");
insert into eerr (prefix, desc) values ("5.3.50","-PERSONAL");
insert into eerr (prefix, desc) values ("5.7.00","-PERSONAL");
insert into eerr (prefix, desc) values ("5.8.00.1010","-COMISIONES");
insert into eerr (prefix, desc) values ("5.8.00.1020","-COMISIONES");
insert into eerr (prefix, desc) values ("5.8.00.1030","-COMISIONES");
insert into eerr (prefix, desc) values ("5.8.00.1080","-INCENTIVOS ANUALES");
insert into eerr (prefix, desc) values ("5.9.00","-PERSONAL");
insert into eerr (prefix, desc) values ("6.1.00.1000","-HONORARIOS");
insert into eerr (prefix, desc) values ("6.1.00.2000","-ASESORIAS");
insert into eerr (prefix, desc) values ("6.1.00.3000","-OTRAS ASESORIAS");
insert into eerr (prefix, desc) values ("6.1.50","-SEGUROS");
insert into eerr (prefix, desc) values ("6.2.00","-FLETES");
insert into eerr (prefix, desc) values ("6.3.00","-ARRIENDOS");
insert into eerr (prefix, desc) values ("6.4.01","-GASTOS DE VIAJE");
insert into eerr (prefix, desc) values ("6.4.02","-GASTOS DE VIAJE");
insert into eerr (prefix, desc) values ("6.5.00","-GASTOS GENERALES");
insert into eerr (prefix, desc) values ("6.5.50","-GASTOS SERVICIOS");
insert into eerr (prefix, desc) values ("6.6.00","-IMPUESTOS Y PATENTES");
insert into eerr (prefix, desc) values ("6.8.00","-DEPRECIACION");
insert into eerr (prefix, desc) values ("7.0.00.9090","-PUBLICIDAD");
insert into eerr (prefix, desc) values ("7.0.00.1000","-PUBLICIDAD");
insert into eerr (prefix, desc) values ("7.0.00.3000","-PROMOTORES");
insert into eerr (prefix, desc) values ("7.1.00","-OTROS INGRESOS OPERACIONALES");
insert into eerr (prefix, desc) values ("9.0.00.1010","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1015","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1020","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1030","-USD");
insert into eerr (prefix, desc) values ("9.0.00.1035","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1040","-USD");
insert into eerr (prefix, desc) values ("9.0.00.1050","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1055","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1070","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.1090","-IPC-UF");
insert into eerr (prefix, desc) values ("9.0.00.2010","-USD");
insert into eerr (prefix, desc) values ("9.0.00.2015","-USD");
insert into eerr (prefix, desc) values ("9.0.00.2020","-USD");
insert into eerr (prefix, desc) values ("9.0.00.2030","-USD");
insert into eerr (prefix, desc) values ("9.0.00.2040","-IPC-UF");
insert into eerr (prefix, desc) values ("9.1.00.1015","-USD");
insert into eerr (prefix, desc) values ("9.1.00.1020","-USD");
insert into eerr (prefix, desc) values ("9.1.00.1030","-USD");
insert into eerr (prefix, desc) values ("9.1.00.1045","-IPC-UF");
insert into eerr (prefix, desc) values ("9.1.00.2025","-IPC-UF");
insert into eerr (prefix, desc) values ("9.1.00.2026","-IPC-UF");
insert into eerr (prefix, desc) values ("9.3.00.1010","-USD");