insert into area (area, marca, agrupacion) values (10,"IQUIQUE","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (11,"SAMSUNG","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (12,"IRT","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (13,"BENQ","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (14,"PIONEER","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (15,"SOPORTE IQUIQUE","RCL SERVICIOS");
insert into area (area, marca, agrupacion) values (16,"FUJITEL","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (17,"AOC","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (18,"HONEYWELL","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (19,"PRINCESS","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (20,"GENERAL ELECTRIC","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (21,"KINGSTON","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (22,"LOGITECH","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (23,"TP-LINK","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (24,"AUDIOLAB","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (25,"GOLLA","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (26,"HP","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (27,"LEXAR","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (28,"MINWA","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (29,"TOSHIBA","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (30,"UNI-T","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (31,"CREATIVE","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (32,"MOTOROLA","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (33,"MEMOREX","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (34,"XTREMEMAC","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (49,"OTRAS MARCAS","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (51,"SOPORTE  ","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (70,"SERVICIO TÉCNICO","RCL SERVICIOS");
insert into area (area, marca, agrupacion) values (79,"RETAIL","#N/A");
insert into area (area, marca, agrupacion) values (80,"LOGISTICA","RCL SERVICIOS");
insert into area (area, marca, agrupacion) values (90,"OTROS NEGOCIOS","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (92,"ADMINISTRACIÓN","RCL COMERCIAL");
insert into area (area, marca, agrupacion) values (93,"FINANZAS","RCL SERVICIOS");
insert into area (area, marca, agrupacion) values (95,"OTROS GASTOS","RCL SERVICIOS");
insert into area (area, marca, agrupacion) values (99,"SIN DEFINICIÓN","RCL COMERCIAL");
